gaussian_blur_size: 7
gaussian_blur_sigma: 2.08
canny_edge_th: 93
hough_accum_resolution: 1.05
min_circle_dist: 140.6
hough_accum_th: 74.10000000000001
min_radius: 65
max_radius: 486
filter_h_min: 356
filter_h_max: 10
filter_s_min: 254
filter_s_max: 255
filter_v_min: 25
filter_v_max: 160
use_second_filter: false
filter2_h_min: 42
filter2_h_max: 345
filter2_s_min: 32
filter2_s_max: 190
filter2_v_min: 48
filter2_v_max: 252
ellipse_size: 3
filter_debug: false